### PR TITLE
Features: added two buttons for tweeting international media houses 

### PR DESCRIPTION
**Pull request by kalikim**
**Description**

Added functionality to tweet to international media houses regarding the #RejectFinanceBill2024 campaign. This includes two buttons: one optimized for premium Twitter users and another for non-premium users due to character limitations.

**Changes Made:**

Added two new buttons to the tweet interface:
Tweet International Media Houses: Designed for premium Twitter users, allowing inclusion of a comprehensive list of usernames and the campaign hashtag.
Tweet International Media Houses (Non-Premium): Optimized for non-premium Twitter users by limiting usernames to 8 major media houses and focusing on the campaign hashtag to fit within Twitter's 280-character limit.
Reason for Two Buttons:

Premium vs. Non-Premium Users: Twitter's character limit for non-premium users necessitates a streamlined tweet format to effectively reach international media.
Enhanced Campaign Reach: Provides flexibility for users to engage with a broader audience including major media outlets, amplifying the #RejectFinanceBill2024 message globally.

### CODE REVIEW

**Review by StanleyMasinde — CHANGES_REQUESTED** [review]
add the .idea directory to .gitignore. Otherwise it looks good.

**Review by kalikim — COMMENTED** [review]
i have updated the gitignore file

**Comment by kalikim** [comment]
@StanleyMasinde check the changes as requested

**Comment by StanleyMasinde** [comment]
One list thing, `git rm -r --cached .idea/` To untack the files in .idea

**Review by StanleyMasinde — APPROVED** [review]

**Pull request merged**
