### PR TITLE
Enhancements and Improvements

### PR DESCRIPTION
**Pull request by JudahSan**
- [x] added button/container hover effects for better UX
- [x] enhanced textarea focus style

### CODE REVIEW

**Comment by StanleyMasinde** [comment]
Hi @JudahSan Could you please fix the merge conflicts from your side?

**Comment by JudahSan** [comment]
@StanleyMasinde Fixed

**Comment by StanleyMasinde** [comment]
Please resolve the conflicts

**Comment by StanleyMasinde** [comment]
Please fix the conflicts.

**Comment by JudahSan** [comment]
@StanleyMasinde conflicts fixed

**Pull request merged**
